USE CinemaManagement;
GO
ALTER TABLE chat_messages ALTER COLUMN role VARCHAR(50);
ALTER TABLE chat_messages ALTER COLUMN content NVARCHAR(MAX) NULL;
GO
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'chat_messages';
GO
